In [1]:
text = "John likes to watch movies. Mary likes movies too.\
 Mary also likes to watch football games."
words = text.replace('.', '').split()
words

['John',
 'likes',
 'to',
 'watch',
 'movies',
 'Mary',
 'likes',
 'movies',
 'too',
 'Mary',
 'also',
 'likes',
 'to',
 'watch',
 'football',
 'games']

In [2]:
import numpy as np
word_count = np.unique(words, return_counts=True)
word_count

(array(['John', 'Mary', 'also', 'football', 'games', 'likes', 'movies',
        'to', 'too', 'watch'], dtype='<U8'),
 array([1, 2, 1, 1, 1, 3, 2, 2, 1, 2]))

In [3]:
#딕셔너리 TF 생성
word_to_cnt = {}
for word, cnt in zip(*word_count):
  word_to_cnt[word] = cnt
  
word_to_cnt

{np.str_('John'): np.int64(1),
 np.str_('Mary'): np.int64(2),
 np.str_('also'): np.int64(1),
 np.str_('football'): np.int64(1),
 np.str_('games'): np.int64(1),
 np.str_('likes'): np.int64(3),
 np.str_('movies'): np.int64(2),
 np.str_('to'): np.int64(2),
 np.str_('too'): np.int64(1),
 np.str_('watch'): np.int64(2)}

In [4]:
word_to_cnt['movies']

np.int64(2)

In [5]:
corpus = [
    "John likes to watch movies. Mary likes movies too.",
    "Mary also likes to watch football games."
]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
dtm_array = vector.fit_transform(corpus).toarray()
dtm_array

array([[0, 0, 0, 1, 2, 1, 2, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 0, 1]])

In [7]:
tf_dic = vector.vocabulary_
print(vector.vocabulary_)

{'john': 3, 'likes': 4, 'to': 7, 'watch': 9, 'movies': 6, 'mary': 5, 'too': 8, 'also': 0, 'football': 1, 'games': 2}

In [8]:
import pandas as pd
tf_dic_sorted = dict(sorted(tf_dic.items(), key=lambda item: item[1]))
#tf_dic_sorted
df = pd.DataFrame(dtm_array, columns=tf_dic_sorted.keys())
df

   also  football  games  john  likes  mary  movies  to  too  watch
0     0         0      0     1      2     1       2   1    1      1
1     1         1      1     0      1     1       0   1    0      1

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer()
tfidf_array = tfidf_vec.fit_transform(corpus).toarray()
#tfidf_array

In [10]:
tfidf_dic = tfidf_vec.vocabulary_
#tfidf_dic
tfidf_dic_sorted = dict(sorted(tfidf_dic.items(), key=lambda item: item[1]))
tfidf_dtm = pd.DataFrame(tfidf_array, columns=tfidf_dic_sorted.keys())
tfidf_dtm

,also,football,games,john,likes,mary,movies,to,too,watch
0,0.000000,0.000000,0.000000,0.323699,0.460629,0.230315,0.647398,0.230315,0.323699,0.230315
1,0.446101,0.446101,0.446101,0.000000,0.317404,0.317404,0.000000,0.317404,0.000000,0.317404

In [12]:
!pip install --upgrade gensim

Requirement already satisfied: gensim in /home/ubuntu/q/envs/dl_env/lib/python3.11/site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /home/ubuntu/q/envs/dl_env/lib/python3.11/site-packages (from gensim) (2.4.3)
Requirement already satisfied: scipy>=1.7.0 in /home/ubuntu/q/envs/dl_env/lib/python3.11/site-packages (from gensim) (1.17.1)
Requirement already satisfied: smart_open>=1.8.1 in /home/ubuntu/q/envs/dl_env/lib/python3.11/site-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /home/ubuntu/q/envs/dl_env/lib/python3.11/site-packages (from smart_open>=1.8.1->gensim) (2.1.2)

In [13]:
!pip install "scipy<1.11"

Collecting scipy<1.11
  Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
Collecting numpy<1.27.0,>=1.19.5 (from scipy<1.11)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Downloading scipy-1.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 24.5 MB/s  0:00:01 eta 0:00:01
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 37.4 MB/s  0:00:00 eta 0:00:01
Installing collected packages: numpy, scipy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
  Attempting uninstall: scipy━━━━━━━━━━━━━━━━━━━ 0/2 [numpy]
    Found existing installation: scipy 1.17.1[0m 0/2 [numpy]
    Uninstalling scipy-1.17.1:━━━━━━━━━━━━━━ 0/2 [numpy]
      Successfully uninstalled scipy-1.17.1━ 0/2 [numpy]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [scipy]32m1/2 [scipy]
Successfully installed numpy-1.26.4 scipy-1.10.1

In [14]:
from gensim.models import Word2Vec
corpus = [
    "John likes to watch movies. Mary likes movies too.",
    "Mary also likes to watch football games."
]
word_list = []

In [15]:
for word in corpus:
  word_list.append(word.replace('.','').split())
  
word_list

[['John', 'likes', 'to', 'watch', 'movies', 'Mary', 'likes', 'movies', 'too'],
 ['Mary', 'also', 'likes', 'to', 'watch', 'football', 'games']]

In [16]:
model = Word2Vec(word_list, sg=0, vector_size=100, window=3, min_count=1)
model.wv.most_similar('likes', 'movies')

[('John', 0.1716446876525879),
 ('also', 0.06594576686620712),
 ('Mary', 0.008838452398777008),
 ('watch', -0.06765827536582947),
 ('games', -0.08544929325580597),
 ('football', -0.08948154002428055),
 ('too', -0.11860240250825882),
 ('to', -0.13643862307071686)]

In [17]:

model = Word2Vec(word_list, sg=1, vector_size=100, window=3, min_count=1)
model.wv.most_similar('likes', 'movies')

[('John', 0.1716446876525879),
 ('also', 0.06594576686620712),
 ('Mary', 0.008853347040712833),
 ('watch', -0.06765827536582947),
 ('games', -0.08544929325580597),
 ('football', -0.08948154002428055),
 ('too', -0.11860240250825882),
 ('to', -0.13643866777420044)]

In [18]:
model = Word2Vec(word_list, sg=1, vector_size=100, window=3, min_count=1)
model.wv.most_similar('games')

[('to', 0.13887982070446014),
 ('watch', 0.13149002194404602),
 ('movies', 0.06408979743719101),
 ('too', 0.06059185788035393),
 ('football', 0.019152285531163216),
 ('Mary', 0.009383060969412327),
 ('also', -0.05774582922458649),
 ('likes', -0.05987628921866417),
 ('John', -0.10513810068368912)]